Workaround to prevent TLS handshakes to hang the server
sepalani/MH3SP pull request #121
Opened 2023-10-21 21:38 UTC by sepalani

Generic alternative to https://github.com/sepalani/MH3SP/pull/120.

2023-10-22 13:27 UTC, InusualZ requested changes
As per the stackoverflow's [post](https://stackoverflow.com/a/68214507) that you linked. We have to timeout non-responsive TCP connections. I suppose that's handled by the previous `client_socket.settimeout` which is nice.

2023-10-22 13:27 UTC, InusualZ commented on mh/server.py
> +        # type: (Tuple[str, int], BasicPatHandler, int, bool, str, str) -> None
```py
# type: (Tuple[str, int], BasicPatHandler, int, bool, Optional[str], Optional[str]) -> None
```

Or (if you don't want to do ```from typing import Optional```)
```py
# type: (Tuple[str, int], BasicPatHandler, int, bool, str|None, str|None) -> None
```

2023-10-22 17:22 UTC, sepalani commented
> As per the stackoverflow's [post](https://stackoverflow.com/a/68214507) that you linked. We have to timeout non-responsive TCP connections. I suppose that's handled by the previous `client_socket.settimeout` which is nice.

@InusualZ 
Yeah, we've already used the `settimeout` to handle ill-formed packets. If we find another way to handle them, we'd have to restore the previous timeout setting after calling the SSL wrap function. I also addressed your comment.

Code seems good to me, I still need to test in on real hardware to make sure it doesn't introduce regressions.

2023-10-22 17:35 UTC, InusualZ approved these changes

2023-10-25 18:10 UTC, sepalani commented
Tested and working on real hardware.

2023-10-25 18:11 UTC, merged