PAT: Check that the handler (still) exists before a broadcast
sepalani/MH3SP pull request #30
Opened 2022-01-26 18:06 UTC by sepalani

This PR fixes a bug when, in some circumstances like disconnection or race condition, the `pat_handler` is `None` and try to call the `send_packet` method.

2022-01-26 18:15 UTC, InusualZ commented
I thought about doing this, but I thought that in the cases that we weren't receiving a proper `pat_handler` was because we weren't clearing the session from the layers properly. So, I thought that #28 would fix the issue

2022-01-26 18:24 UTC, sepalani commented
That's one of the case but I'm pretty sure it can happen with a race condition too. Since there are 2 threads running in parallel, the one from the session which is going to be deleted and the one who wants to perform a broadcast.

However, now that I think about it, this simple approach won't work because network errors can occur too and we don't want a partial broadcast failure to kick the player. I'll give it some thought. I have different ideas in mind like:
 * Wrapping it in a `try..except` block _(quick and dirty approach, IMO)_
 * Adding a queue system somewhere in the server thread (not the player one)
   - Maybe during the `select` loop.
   - Need more thought and might be slower, too

I'll turn it into a draft for now.

2022-08-27 16:03 UTC, sepalani commented
Rather than creating a wrapper class, I created a proper method that handles exception. This should avoid to use wrapper or any magic tricks that can make the code harder to follow.

2022-09-01 12:18 UTC, InusualZ requested changes
Logic look sane, 1 comment though.

2022-09-01 12:18 UTC, InusualZ commented on mh/pat.py
> +            self.server.warning(
I think a more useful information would be the exception message. Having the packet info doesn’t tell me anything what really happened.

2022-09-01 18:47 UTC, sepalani commented
@InusualZ 
Done. I added the traceback in the log message.

2022-09-01 19:06 UTC, merged